/** Central TanStack Query keys – keeps invalidation consistent. */
export const queryKeys = {
  categories: ['categories'] as const,
  progress: ['progress'] as const,
  categoryStats: ['stats', 'categories'] as const,
  topicStats: ['stats', 'topics'] as const,
  wrongQuestions: ['stats', 'wrong-questions'] as const,
  difficultyStats: ['stats', 'difficulty'] as const,
  categoryQuestions: ['stats', 'category-questions'] as const,
  savedQuestions: ['saved-questions'] as const,
  savedQuestionIds: ['saved-questions', 'ids'] as const,
  sessionQuestions: ['activity', 'session-questions'] as const,
  dailyQuiz: ['activity', 'daily'] as const,
  dailyTasks: ['activity', 'daily-tasks'] as const,
  dailyWheel: ['activity', 'daily-wheel'] as const,
  completedSession: ['activity', 'completed-session'] as const,
  profile: ['profile'] as const,
  perfectSessions: ['stats', 'perfect-sessions'] as const,
  myIdeas: ['ideas', 'mine'] as const,
  studySheets: ['study-sheets'] as const,
  studyFolders: ['study-sheets', 'folders'] as const,
  unreadMessages: ['friends', 'unread'] as const,
  modeRecords: ['stats', 'mode-records'] as const,
  answerStats: ['stats', 'answers'] as const,
  friends: ['friends'] as const,
  friendRequests: ['friends', 'requests'] as const,
  friendProfile: ['friends', 'profile'] as const,
  userSearch: ['friends', 'search'] as const,
  conversation: ['friends', 'conversation'] as const,
  blocks: ['friends', 'blocks'] as const,
  duel: ['friends', 'duel'] as const,
  dailyHistory: ['stats', 'history'] as const,
  accuracyTrend: ['stats', 'trend'] as const,
  totals: ['stats', 'totals'] as const,
  playedDays: ['stats', 'played-days'] as const,
} as const;
